### ISSUE TITLE
The app crashes when a subthread of a thread is created where both thread and subthread contains only currently logged in user

### ISSUE THREAD

**Issue by zrebcu411** [Ashoat/squadcal#66]
Steps to reproduce: 

Assume that `john` is a currently logged in user.

1. Go to a thread where `john` is an only user
2. Go to thread settings, click `Add child thread` then select `Open` option
3. Do not add any users, just click the `Create` button
4. Confirm alert that says: `Chatting to yourself?`
5. The app will crash

![image](https://user-images.githubusercontent.com/23239447/84041694-6d32d500-a9a4-11ea-8275-dbab9e32db77.png)

![image](https://user-images.githubusercontent.com/23239447/84042209-0feb5380-a9a5-11ea-9da7-e563c1e9b18a.png)

**Comment by Ashoat** [comment]
Thanks for this bug report. 

There are several places in the code where I keep track of a `ThreadInfo` object in a screen's params, so that if that `ThreadInfo` gets removed from Redux the component will still have access to the old data while it animates away.

In those cases I set up the code to update the `ThreadInfo` whenever it changed. We got this error because an update occurred after the screen had been removed from the routes.

This begs the question - what update? The error shows an update to the parent thread, but in fact the objects are identical.

What's going on - whenever the `threadStore.threadInfos` gets changed at all, the code currently forces every `ThreadInfo` to be recomputed from the `RawThreadInfo`. So when the child thread appeared, it forced a recomputation of the parent thread, creating a new object. Even though the new object looks the same, every component that uses the old `ThreadInfo` treats this like a change.

This is incredibly wasteful and very bad for performance. To be honest I don't know why I didn't notice it sooner.

I just fixed it by using `reselect-map` to make sure each individual object (across `threadStore`, `messageStore`, and `entryStore`) is memoized on its own. Unfortunately any change to `userInfos` still forces every store to update, but these changes should be rare (for now).
